version: '2'
services:
 web:
   image: vultarget/ghostscript_rce-cve_2018_19475:9.25
   command: php -t /var/www/html -S 0.0.0.0:8080
   volumes:
    - ./index.php:/var/www/html/index.php
   ports:
    - "8080:8080"
