version: '2'
services:
 kibana:
   image: vultarget/kibana_rce-cve_2019_7609:6.5.4
   depends_on:
    - elasticsearch
   ports:
    - "5601:5601"
 elasticsearch:
   image: vultarget/elasticsearch_rce-cve_2019_7609:6.8.6
