version: '2'
services:
 web:
   image: vultarget/phpmyadmin_rce-cve_2016_5734:4.4.15.6
   volumes:
    - ./config.inc.php:/var/www/html/config.inc.php
   ports:
    - "8080:80"
   depends_on:
    - mysql
 mysql:
   image: mysql:5.5
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
