version: '2'
services:
 kibana:
   image: vultarget/kibana_file_inclusion-cve_2018_17246:5.6.12
   depends_on:
    - elasticsearch
   ports:
    - "5601:5601"
 elasticsearch:
   image: vultarget/elasticsearch_file_inclusion-cve_2018_17246:5.6.16
