version: '2'
services:
 web:
   image: vultarget/drupal_sqli-cve_2014_3704:7.31
   depends_on:
    - mysql
   ports:
    - "8080:80"
 mysql:
   image: mysql:5.5
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=drupal
