wordpress:
  image: vultarget/wordpress_redux-cve_2021_38314:4.2.11
  ports:
    - 80:80
  links:
    - db:mysql
  volumes:
    - ./wordpress:/var/www/html
  environment:
    WP_VERSION: 5.4.2

db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: password
