version: '2'
services:
 nginx:
   image: vultarget/nginx_bypass_rce-cve_2013_4547:1.4.2 
   volumes:
    - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    - ./www:/usr/local/nginx/html
   ports:
    - "8080:80"
 php:
   build: ./php-fpm/
   volumes:
    - ./www:/var/www/html
