version: '2'
services:
  web:
    image: vultarget/django_sqli-cve_2019_14234:2.2.3
    ports:
    - "8000:8000"
    depends_on:
    - db
  db:
   image: postgres:9.6-alpine
   environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=cve
