version: '3'
services:
 web:
   image: vultarget/ghostscript_rce-cve_2019_6116:9.26
   command: php -t /var/www/html -S 0.0.0.0:8080
   volumes:
    - ./index.php:/var/www/html/index.php
   ports:
    - "8080:8080"
